name: "Build Configuration"

inputs:
  KEYSTORE_BASE64:
    required: true
  KEYSTORE_PASSWORD:
    required: true
  KEY_PASSWORD:
    required: true
  KEY_ALIAS:
    required: true

runs:
  using: 'composite' # 외부에서 사용하도록 처리
  steps:
    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew
      shell: bash


    - name: Decode keystore from base64
      run: |
        echo "${{ inputs.KEYSTORE_BASE64 }}" | base64 -d > yapp.keystore
      shell: bash
      

    - name: Generate keystore.properties
      run: |
        echo "store.file.path=yapp.keystore" > keystore.properties
        echo "store.password=${{ inputs.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "key.password=${{ inputs.KEY_PASSWORD }}" >> keystore.properties
        echo "key.alias=${{ inputs.KEY_ALIAS }}" >> keystore.properties
      shell: bash



