name: "Detekt With Reviewdog"
description: "내부 코드 품질 개선 액션"

inputs:
  GH_TOKEN:
    description: 'github token in actions'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Detekt
      shell: bash
      run: ./gradlew detekt --continue

    - name: Run Reviewdog on Detekt
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="detekt" -reporter=github-pr-review -level=info
