on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: true
          ref: ${{ inputs.ref }}

      - id: build-configuration
        name: Build Configuration
        uses: ./.github/actions/build-configuration
        with:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          BASE_URL_DEBUG: ${{ secrets.BASE_URL_DEBUG }}
          BASE_URL_RELEASE: ${{ secrets.BASE_URL_RELEASE }}
          BASE_URL_QA: ${{ secrets.BASE_URL_QA }}

      - id: dekekt
        name: Dekekt
        uses: ./.github/actions/detekt
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

